# Deployment for the containers/pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-app
  labels:
    app: gateway-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server-app
  template:
    metadata:
      labels:
        app: gateway-server-app
    spec:
      containers:
        - name: gateway-container
          image: chabrik/gatewayserver
          imagePullPolicy: Always
          ports:
            - containerPort: 9004

---
# Service for the containers/pods
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-server-app
  type: LoadBalancer  
  ports:
    - port: 80
      targetPort: 9004
      protocol: TCP