# Deployment for the containers/pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-app
  labels:
    app: gateway-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server-app
  template:
    metadata:
      labels:
        app: gateway-server-app
    spec:
      containers:
        - name: gateway-container
          image: chabrik/gatewayserver
          imagePullPolicy: Always
          ports:
            - containerPort: 9004
