# Deployment for the containers/pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-produits-app
  labels:
    app: microservice-produits-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-produits-app
  template:
    metadata:
      labels:
        app: microservice-produits-app
    spec:
      containers:
        - name: product-container
          image: chabrik/mproduits
          imagePullPolicy: Always
          ports:
            - containerPort: 9001